### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nico-mayora** [nico-mayora/BusAppPrototype#1]
- [ ] Show user's current location
- [ ] Filter buses by company, subsystem, and line
- [ ] Show filtered buses' current location ( found in :geometry, :coordinates)
- [ ] Filter by bus direction
